# Generated by Django 4.2.5 on 2024-01-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_url_document_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uuid',
            new_name='ref',
        ),
    ]
