# Generated by Django 4.2.5 on 2024-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_uuid_document_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='✨ New markdown document', max_length=256),
        ),
        migrations.AlterField(
            model_name='document',
            name='contents',
            field=models.TextField(blank=True, default='Hi there! 👋'),
        ),
    ]
